 <!-- Jquery Js -->
 <script src="{{ asset('/') }}website/assets/js/vendor/bootstrap.min.js"></script>
 <script src="{{ asset('/') }}website/assets/js/vendor/jquery-3.6.3.min.js"></script>
 <script src="{{ asset('/') }}website/assets/js/vendor/slick.min.js"></script>
 <script src="{{ asset('/') }}website/assets/js/vendor/jquery-validator.js"></script>
 <script src="{{ asset('/') }}website/assets/js/vendor/jquery.countdown.min.js"></script>
 <script src="{{ asset('/') }}website/assets/js/vendor/countryCode.js"></script>
 <script src="{{ asset('/') }}website/assets/js/vendor/picker.js"></script>
 <script src="{{ asset('/') }}website/assets/js/vendor/picker.date.js"></script>
 <script src="{{ asset('/') }}website/assets/js/date.js"></script>
 <script src="{{ asset('/') }}website/assets/js/app.js"></script>
